version: '3'
services:
  api:
    container_name: app
    build:
      context: ./backend-api
    image: app:latest
    ports:
      - ${API_SERVER_PORT}:80
    volumes:
      - ./backend-api:/var/www
    links:
      - mysql
      - redis
    environment:
      DB_HOST: mysql
      DB_DATABASE: bp
      DB_USERNAME: bpuser
      DB_PASSWORD: bppassword
      REDIS_URL: redis://cache
    expose:
      - ${API_SERVER_PORT}
  mysql:
    image: mysql:5.7
    container_name: database
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: bp
      MYSQL_USER: bpuser
      MYSQL_PASSWORD: bppassword
      MYSQL_ROOT_PASSWORD: password
